apiVersion: v1
kind: Service
metadata:
  labels:
    app: suber
  name: suber
  namespace: default
spec:
  ports:
  - nodePort: 30568
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: suber
  sessionAffinity: None
  type: LoadBalancer

